#!/usr/bin/env sh

# change these to match your system
OS="darwin"   # or linux
ARCH="x64"
VERSION="$1"
PREFIX=~

# if no version specified, bail
[ -z "$VERSION" ] && echo "please specify a version (like v0.9.5)" > /dev/stderr && exit 1

# some vars
NODE_NAME=node-"$VERSION"-"$OS"-"$ARCH"

# make sure we at least have a lib dir
mkdir -p "$PREFIX"/lib
cd "$PREFIX"/lib

# if we don't have the requested version in lib 
# try to download it from nodejs.org
if [ ! -d "$NODE_NAME" ]
then
  echo "version $VERSION not found, attempting to download..."
  curl -O http://nodejs.org/dist/"$VERSION"/"$NODE_NAME".tar.gz
  tar -xvzf "$NODE_NAME".tar.gz
  rm -rf "$NODE_NAME".tar.gz
fi

# make sure it downloaded
[ ! -d "$NODE_NAME" ] && echo "version $VERSION could not be downloaded, exiting" > /dev/stderr && exit 1
cd "$NODE_NAME"

# if we got this far, we have the right version
# so we just symlink the contents of any directories 
# inside lib/<node-version> out to their corresponding 
# locations in $PREFIX/
ls | while read LISTING
do
  if [ -d "$LISTING" ]
  then
    mkdir -p "$PREFIX"/"$LISTING"
    ls "$LISTING" | while read FILE
    do
        ln -sF $(pwd)/"$LISTING"/"$FILE" "$PREFIX"/"$LISTING"
    done
  fi
done
